In [18]:
import torch
import torch.nn as nn
from src.agent_logic import Agent
from src.game_logic import Game
import pandas
from matplotlib import pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [2]:
def play_game(game, agent):
    while not game.game_over():
        # Calculate q value for each action from state
        state_values = agent._model(game.state.flatten(1).float())
        # Flag futile actions
        state_values[game.available_actions().logical_not()] = -1
        # Choose action with max q_value
        actions = state_values.max(1)[1]
        # Do Action
        game.do_action(actions.to(torch.int8), 1)

## Init Agent

In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [4]:
model = nn.Sequential(
    nn.Linear(16, 16),
    nn.Hardsigmoid(),
    nn.Linear(16, 16),
    nn.Hardsigmoid(),
    nn.Linear(16, 8),
    nn.Hardsigmoid(),
    nn.Linear(8, 4),
    nn.Hardsigmoid(),
)

In [5]:
agent = Agent(device, model)

In [6]:
game = Game(5, 4)

In [7]:
play_game(game, agent)

In [8]:
game.state

tensor([[[2, 1, 2, 1],
         [3, 2, 3, 2],
         [5, 4, 2, 3],
         [7, 2, 4, 1]],

        [[2, 1, 2, 1],
         [5, 4, 1, 2],
         [1, 6, 2, 3],
         [4, 2, 4, 1]],

        [[4, 3, 2, 1],
         [5, 4, 3, 4],
         [6, 5, 6, 3],
         [8, 3, 2, 1]],

        [[4, 3, 2, 1],
         [5, 4, 3, 2],
         [6, 5, 4, 3],
         [8, 6, 5, 1]],

        [[2, 1, 2, 1],
         [4, 3, 5, 2],
         [5, 4, 3, 4],
         [7, 5, 2, 1]]], device='cuda:0', dtype=torch.uint8)

In [9]:
game.score

tensor([ 988,  576, 2808, 2900, 1280], device='cuda:0', dtype=torch.int32)

In [10]:
model.load_state_dict(torch.load('model1.pt'))

<All keys matched successfully>

In [11]:
game = Game(5, 4)

In [12]:
play_game(game, agent)

In [13]:
game.state

tensor([[[1, 2, 3, 4],
         [2, 3, 4, 5],
         [1, 7, 1, 6],
         [3, 1, 2, 7]],

        [[1, 2, 3, 4],
         [2, 3, 1, 6],
         [4, 5, 4, 7],
         [1, 2, 8, 1]],

        [[1, 2, 3, 4],
         [4, 3, 4, 5],
         [2, 5, 1, 7],
         [1, 3, 4, 9]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5],
         [3, 4, 5, 1],
         [2, 5, 7, 3]],

        [[2, 1, 3, 4],
         [3, 2, 4, 5],
         [1, 4, 5, 6],
         [2, 6, 1, 8]]], device='cuda:0', dtype=torch.uint8)

In [14]:
game.score

tensor([2072, 3084, 5232, 1328, 2764], device='cuda:0', dtype=torch.int32)

In [16]:
training = pandas.read_csv('trial1.csv')

In [20]:
training.round(2)

Unnamed: 0  Time (s)     Mean      Std
0             0     23.63  1040.20   512.06
1             1     48.31  1036.40   509.77
2             2     71.79  1102.10   538.49
3             3     94.81  1102.59   538.37
4             4    120.63  1103.69   538.41
..          ...       ...      ...      ...
995         995  36384.75  2206.73  1096.89
996         996  36426.41  2205.68  1096.91
997         997  36463.91  2205.50  1096.65
998         998  36504.03  2203.89  1093.94
999         999  36539.68  2208.55  1097.02

[1000 rows x 4 columns]