In [1]:
from src.game_logic import Game

In [2]:
game = Game(int(2e0), 4)

In [3]:
game.state

tensor([[[0, 0, 1, 0],
         [0, 1, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [1, 0, 1, 0]]], device='cuda:0', dtype=torch.uint8)

In [12]:
game.game_over(dim=1)

tensor([False, False], device='cuda:0')

In [15]:
import torch

In [17]:
torch.arange(4)

tensor([0, 1, 2, 3])

In [25]:
test = torch.arange(16).reshape(4, 4)

In [35]:
test.gather(1, torch.arange(4).unsqueeze(1)).squeeze()

tensor([ 0,  5, 10, 15])