In [1]:
from src import Game
import torch

In [2]:
device = torch.device('cuda')

In [3]:
game = Game(batch_size=2, device=device)

In [4]:
game.state

tensor([[[0, 0, 0, 0],
         [0, 1, 0, 0],
         [0, 0, 1, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [1, 0, 1, 0]]], device='cuda:0', dtype=torch.uint8)

In [5]:
game.score

tensor([0, 0], device='cuda:0', dtype=torch.int32)

In [6]:
game.game_over()

tensor(False, device='cuda:0')

In [7]:
if game.batch_size > 0:
    print(game.game_over(dim=1))

tensor([False, False], device='cuda:0')


In [8]:
game.available_actions()

tensor([[1, 1, 1, 1],
        [1, 1, 1, 0]], device='cuda:0', dtype=torch.uint8)

In [9]:
game.check_action(0)

tensor([1, 1], device='cuda:0', dtype=torch.uint8)

In [10]:
game.do_action(0)

tensor([0, 4], device='cuda:0', dtype=torch.int32)

In [11]:
game.state

tensor([[[0, 0, 0, 0],
         [1, 0, 0, 0],
         [1, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [2, 0, 0, 0]]], device='cuda:0', dtype=torch.uint8)

In [12]:
game.score

tensor([0, 4], device='cuda:0', dtype=torch.int32)

In [13]:
game.add_tile()

tensor([13, 14], device='cuda:0', dtype=torch.int8)

In [14]:
game.state

tensor([[[0, 1, 0, 0],
         [1, 0, 0, 0],
         [1, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [2, 0, 0, 2]]], device='cuda:0', dtype=torch.uint8)

In [15]:
game.simulate_action(0)

(tensor([0, 8], device='cuda:0', dtype=torch.int32),
 tensor([[[1, 0, 0, 0],
          [1, 0, 0, 0],
          [1, 0, 0, 0],
          [0, 0, 0, 0]],
 
         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [3, 0, 0, 0]]], device='cuda:0', dtype=torch.uint8))

In [16]:
game.state

tensor([[[0, 1, 0, 0],
         [1, 0, 0, 0],
         [1, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [2, 0, 0, 2]]], device='cuda:0', dtype=torch.uint8)

In [17]:
game.score

tensor([0, 4], device='cuda:0', dtype=torch.int32)

In [18]:
game.new_game()

In [19]:
game.state

tensor([[[0, 1, 0, 0],
         [0, 0, 0, 1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [2, 0, 0, 1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]], device='cuda:0', dtype=torch.uint8)

In [20]:
game.score

tensor([0, 0], device='cuda:0', dtype=torch.int32)