In [1]:
from src import Batch
import torch

In [2]:
device = torch.device('cuda')

In [3]:
batch = Batch(size=2, device=device)

In [4]:
batch.rotate(torch.tensor([1, 2], device=device))

In [5]:
batch.can_advance()

tensor([1, 1], device='cuda:0', dtype=torch.uint8)

In [6]:
batch.advance()

tensor([0, 0], device='cuda:0', dtype=torch.int32)

In [7]:
batch.add_tile()

tensor([1, 1], device='cuda:0', dtype=torch.uint8)

In [8]:
batch.sym_rotations_advance()

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], device='cuda:0', dtype=torch.uint8)

In [11]:
batch.game_over(dim=1)

tensor([False, False], device='cuda:0')

In [10]:
batch.states

tensor([[[1, 0, 0, 0],
         [1, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 1]],

        [[0, 0, 0, 0],
         [1, 0, 0, 0],
         [1, 0, 0, 0],
         [0, 0, 2, 0]]], device='cuda:0', dtype=torch.uint8)