In [1]:
from src import Game
import torch

In [2]:
device = torch.device('cpu')

In [3]:
game = Game(batch_size=2, device=device)

In [4]:
game.rotate(torch.tensor([1, 2]))

In [5]:
game.rotation

tensor([1, 2])

In [6]:
game.can_advance()

tensor([1, 1], dtype=torch.uint8)

In [7]:
game.advance()

tensor([0, 4], dtype=torch.int32)

In [8]:
game.add_tile()

In [9]:
game.game_over()

tensor(False)